name: Build GDExtension

on:
  workflow_dispatch:
  push:
    tags: '*'

jobs:
  build:
    strategy:
      matrix:
        target: [template_debug, template_release]
        arch: [x86_32, x86_64]
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            dir: linux
          - os: windows-latest
            platform: windows
            dir: win
          - os: macos-latest
            target: template_debug
            arch: universal
            platform: macos
            dir: osx
          - os: macos-latest
            target: template_release
            arch: universal
            platform: macos
            dir: osx

    runs-on: ${{matrix.os}}
    env:
      SCONS_CACHE: ${{github.workspace}}/.scons_cache
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install multilib
        if: ${{runner.os == 'Linux'}}
        run: sudo apt install gcc-multilib g++-multilib
      - name: Install scons
        run: pip install scons

      - name: Get godot-cpp hash
        shell: bash
        id: godotcpp-hash
        run: echo "hash=$(git submodule | awk '/godot-cpp/ { print $1 }')" >> $GITHUB_OUTPUT

      - name: Extract SDK
        run: |
          aws s3 cp "${{ secrets.AWS_S3_BUCKET }}" sdk.tar.gz
          tar xzf sdk.tar.gz -C sdk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Cache SCons build
        uses: actions/cache@v5
        with:
          path: .scons_cache
          key: scons-${{matrix.platform}}-${{matrix.arch}}-${{matrix.target}}-${{steps.godotcpp-hash.outputs.hash}}-${{hashFiles('src/**')}}
          restore-keys: |
            scons-${{matrix.platform}}-${{matrix.arch}}-${{matrix.target}}-${{steps.godotcpp-hash.outputs.hash}}-
            scons-${{matrix.platform}}-${{matrix.arch}}-${{matrix.target}}-

      - name: Build
        shell: bash
        run: scons platform=${{matrix.platform}} arch=${{matrix.arch}} target=${{matrix.target}}

      - name: Copy SDK binaries
        shell: bash
        run: for dir in sdk/Libraries/${{matrix.dir}}*/; do x=$(basename "$dir"); cp "$dir"/*.{so,dll,dylib} addons/gdgalaxy/"$x" || true; done

      - name: Prepare artifact
        uses: actions/upload-artifact@v6
        with:
          name: gdgalaxy-${{matrix.platform}}-${{matrix.arch}}-${{matrix.target}}
          path: addons/gdgalaxy/${{matrix.dir}}*

  bundle:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - uses: actions/download-artifact@v6
        with:
          path: addons/gdgalaxy
          merge-multiple: true
      
      - name: Copy license and README
        run: cp LICENSE.md README.md addons/gdgalaxy
      
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: gdgalaxy-${{github.ref_name}}-${{github.run_id}}
          path: addons

      - name: Create release zip archive
        if: github.ref_type == 'tag'
        run: zip -r "gdgalaxy-${{github.ref_name}}.zip" addons/*
      - name: Draft release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: "gdgalaxy-${{github.ref_name}}.zip"
